name: Auto-Merge
on:
  pull_request_target:
    types: [opened, reopened]
jobs:
  merge:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check if the PR author made the last commit to the repo 
        run: |
          latest_commit_author=$(git log -1 --pretty=format:'%an')
          echo "latest_commit_author=${latest_commit_author}"
          pr_author_name="${{ github.event.pull_request.user.name }}"
          if [[ "$pr_author_name" == "$latest_commit_author" ]]; then
            echo "Error:: The PR author is the same as the latest commit author."
            exit 1
          fi
          
      - name: Check if number of characters is under 200
        run: |
          # Count the number of characters added in the PR
          added_characters=$(git diff origin/${{ github.event.pull_request.base.ref }} --shortstat | grep -o '[0-9]\+ insertion' | awk '{print $1}' | paste -sd+ - | bc)
          if [[ -z "$added_characters" ]]; then
            added_characters=0
          fi
          echo "added_characters=${added_characters}" >> $GITHUB_ENV

          if [[ "$added_characters" -gt 200 ]]; then
            echo "Error: The number of characters added exceeds the maximum limit of 200."
            exit 1
          fi
      # adapted from https://github.com/maidsafe/pr_size_checker, licensed under MIT
      - name: Get the number of insertions and deletions
        run: |
          insertions=$(git diff --stat origin/${{ github.event.pull_request.base.ref }} | grep -v .lock | grep -v Bin | awk '{print $1}' | sed 's/[^0-9]*//g' | paste -sd+ - | bc)
          deletions=$(git diff --stat origin/${{ github.event.pull_request.base.ref }} | grep -v .lock | grep -v Bin | awk '{print $3}' | sed 's/[^0-9]*//g' | paste -sd+ - | bc)
          
          echo "insertions=${insertions}" >> $GITHUB_ENV
          echo "deletions=${deletions}" >> $GITHUB_ENV

          if [ "$env_insertions" != "1" ] && [ "$env_deletions" != "0" ] || []; then
              echo "Error: The number of lines changes is not allowed."
          fi
         
      
      - name: Merge PR
        run: gh pr merge --auto --rebase "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
