name: Auto-Merge
on:
  pull_request_target:
    types: [opened, reopened]
jobs:
  merge:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get last merged by user
        id: get_last_merged
        run: |
          if [ -f last_merged_by.txt ]; then
            last_merged_user=$(cat last_merged_by.txt)
            echo "::set-output name=last_merged_user::$last_merged_user"
          else
            echo "::set-output name=last_merged_user::"
          fi
      - name: Check if the PR author merged the last PR
        run: |
          pr_author_login="${{ github.event.pull_request.user.login }}"
          echo "pr_author_login=${pr_author_login}"
          last_merged_user="${{ steps.get_last_merged.outputs.last_merged_user }}"
          echo "last_merged_user=${last_merged_user}"

          if [[ -n "$last_merged_user" && "$pr_author_login" == "$last_merged_user" ]]; then
            echo "::error:: The PR author (@$pr_author_login) is the same as the user who merged the last PR (@$last_merged_user)."
            exit 1
          fi

      - name: Check if number of characters is under 200
        run: |
          # Count the number of characters added in the PR
          added_characters=$(git diff origin/${{ github.event.pull_request.base.ref }} --shortstat | grep -o '[0-9]\+ insertion' | awk '{print $1}' | paste -sd+ - | bc)
          if [[ -z "$added_characters" ]]; then
            added_characters=0
          fi

          if [[ "$added_characters" -gt 200 ]]; then
            echo "::error:: The number of characters added exceeds the maximum limit of 200."
            exit 1
          fi
      # adapted from https://github.com/maidsafe/pr_size_checker, licensed under MIT
      - name: Get the number of insertions and deletions
        run: |
          insertions=$(git diff --stat origin/${{ github.event.pull_request.base.ref }} | grep -v .lock | grep -v Bin | awk '{print $1}' | sed 's/[^0-9]*//g' | paste -sd+ - | bc)
          deletions=$(git diff --stat origin/${{ github.event.pull_request.base.ref }} | grep -v .lock | grep -v Bin | awk '{print $3}' | sed 's/[^0-9]*//g' | paste -sd+ - | bc)

          echo "$insertions"
          echo "$deletions"
          # Use the correct syntax to access environment variables
          if [ "$insertions" -ne 1 ] || [ "$deletions" -ne 0 ]; then
              echo "::error::The number of lines changes is not allowed."
              exit 1
          fi
      - name: Merge PR
        id: merge_pr
        run: |
          if gh pr merge --auto --rebase "$PR_URL"; then
            echo "::set-output name=merged::true"
          else
            echo "::set-output name=merged::false"
          fi
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Store merged by user
        if: steps.merge_pr.outputs.merged == 'true'
        run: |
          echo "${{ github.event.pull_request.merged_by.login }}" > last_merged_by.txt
      - name: Upload merged by user artifact
        if: steps.merge_pr.outputs.merged == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: last-merged-by-user
          path: last_merged_by.txt